export const EPS_COLOMBIA = [
  { code: "EPS001", name: "Sanitas" },
  { code: "EPS002", name: "Sura" },
  { code: "EPS003", name: "Nueva EPS" },
  { code: "EPS004", name: "Salud Total" },
  { code: "EPS005", name: "Compensar" },
  { code: "EPS006", name: "Famisanar" },
  { code: "EPS007", name: "Coomeva" },
  { code: "EPS008", name: "Aliansalud" },
  { code: "EPS009", name: "Salud Vida" },
  { code: "EPS010", name: "Comfenalco Valle" },
  { code: "EPS011", name: "Comfamiliar Huila" },
  { code: "EPS012", name: "Comfamiliar Nariño" },
  { code: "EPS013", name: "Humana Viva" },
  { code: "EPS014", name: "Mutual Ser" },
  { code: "EPS015", name: "Coosalud" },
  { code: "EPS016", name: "Aioc" },
  { code: "EPS017", name: "ASMET SALUD" },
  { code: "EPS018", name: "EMSSANAR" },
  { code: "EPS019", name: "Mallamas" },
  { code: "EPS020", name: "Municipal de Cali" },
  { code: "EPS021", name: "SOS" },
  { code: "EPS022", name: "Confamiliar Risaralda" },
  { code: "EPS023", name: "Cruz Blanca" },
  { code: "EPS024", name: "Cafesalud" },
  { code: "EPS025", name: "Saludcoop" },
  { code: "EPS026", name: "Red Salud" },
  { code: "EPS027", name: "Unimodal" },
  { code: "EPS028", name: "Caja de Compensación Familiar de Antioquia" },
  { code: "EPS029", name: "Caja de Compensación Familiar del Cesar" },
  { code: "EPS030", name: "Caja de Compensación Familiar de Boyacá" },
] as const;

export type EPSItem = typeof EPS_COLOMBIA[number];